# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetBasis_swipeable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetBasis_swipeable
    pod "Koloda"

  target 'GetBasis_swipeableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetBasis_swipeableUITests' do
    # Pods for testing
  end

end
